// Circum permission catalog (system-defined). ADR-0004.
// Format: <module>.<resource>.<action>
// This is the single source of truth for permission keys. Seeded into the Permission table
// and referenced by the RBAC can() checks. Phase 1 covers identity/org/audit/session modules;
// later phases add their module permissions using the same convention.

export interface PermissionDef {
  key: string;
  module: string;
  description: string;
}

export const PERMISSION_CATALOG: PermissionDef[] = [
  // identity.users
  { key: "identity.user.read", module: "identity", description: "Read user accounts" },
  { key: "identity.user.create", module: "identity", description: "Create user accounts" },
  { key: "identity.user.update", module: "identity", description: "Update user profile" },
  { key: "identity.user.disable", module: "identity", description: "Disable a user account" },
  { key: "identity.user.reset-password", module: "identity", description: "Reset a user's password" },
  // identity.roles
  { key: "identity.role.read", module: "identity", description: "Read roles and permissions" },
  { key: "identity.role.create", module: "identity", description: "Create custom roles" },
  { key: "identity.role.update", module: "identity", description: "Update role permission grants" },
  // identity.assignments
  { key: "identity.assignment.read", module: "identity", description: "Read role assignments" },
  { key: "identity.assignment.create", module: "identity", description: "Grant a role assignment" },
  { key: "identity.assignment.delete", module: "identity", description: "Revoke a role assignment" },
  // organization
  { key: "org.site.read", module: "org", description: "Read sites" },
  { key: "org.site.create", module: "org", description: "Create sites" },
  { key: "org.site.update", module: "org", description: "Update sites" },
  { key: "org.site.deactivate", module: "org", description: "Deactivate a site" },
  { key: "org.department.read", module: "org", description: "Read departments" },
  { key: "org.department.create", module: "org", description: "Create departments" },
  { key: "org.department.update", module: "org", description: "Update departments" },
  { key: "org.department.deactivate", module: "org", description: "Deactivate a department" },
  // audit
  { key: "audit.read", module: "audit", description: "Read audit events" },
  { key: "audit.export", module: "audit", description: "Export audit events (CSV)" },
  // session
  { key: "session.sign-in", module: "session", description: "Sign in" },
  { key: "session.sign-out", module: "session", description: "Sign out" },
  // employee
  { key: "org.employee.read", module: "org", description: "Read employees" },
  // manufacturing — products (Phase 2)
  { key: "manufacturing.product.read", module: "manufacturing", description: "Read products" },
  { key: "manufacturing.product.create", module: "manufacturing", description: "Create products" },
  { key: "manufacturing.product.update", module: "manufacturing", description: "Update products" },
  // manufacturing — revisions
  { key: "manufacturing.revision.read", module: "manufacturing", description: "Read product revisions" },
  { key: "manufacturing.revision.create", module: "manufacturing", description: "Create product revisions" },
  { key: "manufacturing.revision.update", module: "manufacturing", description: "Update draft revisions" },
  { key: "manufacturing.revision.transition", module: "manufacturing", description: "Transition revision state (approve/effective/etc.)" },
  // manufacturing — BOM
  { key: "manufacturing.bom.read", module: "manufacturing", description: "Read BOMs" },
  { key: "manufacturing.bom.update", module: "manufacturing", description: "Edit BOM lines (draft/in_review revisions only)" },
  // manufacturing — materials
  { key: "manufacturing.material.read", module: "manufacturing", description: "Read materials" },
  { key: "manufacturing.material.create", module: "manufacturing", description: "Create materials" },
  { key: "manufacturing.material.update", module: "manufacturing", description: "Update materials" },
  // manufacturing — material lots (site-scoped)
  { key: "manufacturing.materiallot.read", module: "manufacturing", description: "Read material lots (site-scoped)" },
  { key: "manufacturing.materiallot.create", module: "manufacturing", description: "Receive material lots (site-scoped)" },
  { key: "manufacturing.materiallot.update", module: "manufacturing", description: "Update material lots (site-scoped)" },
  { key: "manufacturing.materiallot.transition", module: "manufacturing", description: "Transition material lot state (site-scoped)" },
  // manufacturing — suppliers
  { key: "manufacturing.supplier.read", module: "manufacturing", description: "Read suppliers" },
  { key: "manufacturing.supplier.create", module: "manufacturing", description: "Create suppliers" },
  { key: "manufacturing.supplier.update", module: "manufacturing", description: "Update suppliers" },
  // manufacturing — material-supplier links
  { key: "manufacturing.materialsupplier.update", module: "manufacturing", description: "Link/unlink material suppliers" },
  // production — routing (Phase 3, global, frozen at EFFECTIVE like BOM)
  { key: "production.routing.read", module: "production", description: "Read routings and operations" },
  { key: "production.routing.update", module: "production", description: "Edit routing operations (draft/in_review revisions only)" },
  // production — work centers (site-scoped)
  { key: "production.workcenter.read", module: "production", description: "Read work centers (site-scoped)" },
  { key: "production.workcenter.create", module: "production", description: "Create work centers (site-scoped)" },
  { key: "production.workcenter.update", module: "production", description: "Update work centers (site-scoped)" },
  // production — work orders (site-scoped)
  { key: "production.workorder.read", module: "production", description: "Read work orders (site-scoped)" },
  { key: "production.workorder.create", module: "production", description: "Create work orders (site-scoped)" },
  { key: "production.workorder.update", module: "production", description: "Update work orders (site-scoped)" },
  { key: "production.workorder.transition", module: "production", description: "Transition work order state (release/complete/close/hold/cancel)" },
  // production — batches (site-scoped)
  { key: "production.batch.read", module: "production", description: "Read manufacturing batches (site-scoped)" },
  { key: "production.batch.create", module: "production", description: "Create batches (site-scoped)" },
  { key: "production.batch.transition", module: "production", description: "Transition batch state (start/complete/ready-for-review/hold)" },
  // production — device lots (site-scoped, split from batch)
  { key: "production.devicelot.read", module: "production", description: "Read device lots (site-scoped)" },
  { key: "production.devicelot.create", module: "production", description: "Split device lots from a batch (site-scoped)" },
  { key: "production.devicelot.transition", module: "production", description: "Transition device lot state" },
  // production — execution (site-scoped)
  { key: "production.execution.read", module: "production", description: "Read operation executions (site-scoped)" },
  { key: "production.execution.create", module: "production", description: "Log operation executions (site-scoped)" },
  // production — material consumption + reservation (site-scoped)
  { key: "production.consumption.read", module: "production", description: "Read material consumptions (site-scoped)" },
  { key: "production.consumption.create", module: "production", description: "Consume material lots against a batch (site-scoped, transactional)" },
  { key: "production.reservation.read", module: "production", description: "Read material reservations (site-scoped)" },
  { key: "production.reservation.create", module: "production", description: "Reserve material lots against a work order (site-scoped)" },
  // production — scrap + rework (site-scoped)
  { key: "production.scrap.read", module: "production", description: "Read scrap records (site-scoped)" },
  { key: "production.scrap.create", module: "production", description: "Record scrap (site-scoped)" },
  { key: "production.rework.read", module: "production", description: "Read rework records (site-scoped)" },
  { key: "production.rework.create", module: "production", description: "Record rework (site-scoped)" },
  // production — shifts (site-scoped)
  { key: "production.shift.read", module: "production", description: "Read shifts (site-scoped)" },
  { key: "production.shift.create", module: "production", description: "Create shifts (site-scoped)" },
  { key: "production.shift.update", module: "production", description: "Update shifts (site-scoped)" },
  // quality — NCR (Phase 4, site-scoped)
  { key: "quality.ncr.read", module: "quality", description: "Read NCRs (site-scoped)" },
  { key: "quality.ncr.create", module: "quality", description: "Create NCRs (site-scoped)" },
  { key: "quality.ncr.transition", module: "quality", description: "Transition NCR state (containment/investigation/disposition/closure)" },
  // quality — Deviation (site-scoped)
  { key: "quality.deviation.read", module: "quality", description: "Read deviations (site-scoped)" },
  { key: "quality.deviation.create", module: "quality", description: "Create deviations (site-scoped)" },
  { key: "quality.deviation.transition", module: "quality", description: "Transition deviation state (assessment/review/closure)" },
  { key: "quality.deviation.approve", module: "quality", description: "Approve a deviation (human-only; AI MUST NEVER)" },
  // quality — Investigation (site-scoped)
  { key: "quality.investigation.read", module: "quality", description: "Read investigations (site-scoped)" },
  { key: "quality.investigation.create", module: "quality", description: "Create investigations (site-scoped)" },
  { key: "quality.investigation.conclude", module: "quality", description: "Conclude an investigation (human-only)" },
  // quality — CAPA (site-scoped). D2 modification: CAPA source is polymorphic.
  { key: "quality.capa.read", module: "quality", description: "Read CAPAs (site-scoped)" },
  { key: "quality.capa.create", module: "quality", description: "Create CAPAs (site-scoped)" },
  { key: "quality.capa.transition", module: "quality", description: "Transition CAPA state (action plan/implementation/effectiveness)" },
  { key: "quality.capa.close", module: "quality", description: "Close a CAPA after human effectiveness verification (AI MUST NEVER)" },
  // quality — Change Control (site-scoped)
  { key: "quality.change.read", module: "quality", description: "Read change controls (site-scoped)" },
  { key: "quality.change.create", module: "quality", description: "Create change controls (site-scoped)" },
  { key: "quality.change.transition", module: "quality", description: "Transition change control state" },
  { key: "quality.change.approve", module: "quality", description: "Approve a change control (human-only; AI MUST NEVER)" },
  // quality — Risk Assessment (site-scoped)
  { key: "quality.risk.read", module: "quality", description: "Read risk assessments (site-scoped)" },
  { key: "quality.risk.create", module: "quality", description: "Create risk assessments (site-scoped)" },
  { key: "quality.risk.update", module: "quality", description: "Update risk assessments (site-scoped)" },
  // lab — Specifications (global, controlled, D7)
  { key: "lab.specification.read", module: "lab", description: "Read specifications" },
  { key: "lab.specification.create", module: "lab", description: "Create specifications" },
  { key: "lab.specification.transition", module: "lab", description: "Transition specification state (approve/effective)" },
  { key: "lab.specification.approve", module: "lab", description: "Approve a specification (human-only; AI MUST NEVER)" },
  // lab — Test Methods (global, controlled)
  { key: "lab.testmethod.read", module: "lab", description: "Read test methods" },
  { key: "lab.testmethod.create", module: "lab", description: "Create test methods" },
  { key: "lab.testmethod.transition", module: "lab", description: "Transition test method state" },
  // lab — Samples (site-scoped)
  { key: "lab.sample.read", module: "lab", description: "Read samples (site-scoped)" },
  { key: "lab.sample.create", module: "lab", description: "Draw samples (site-scoped)" },
  { key: "lab.sample.transition", module: "lab", description: "Transition sample state (receive/test/consume/retain)" },
  // lab — Test Results (site-scoped, D5: eval != disposition; disposition is human-only)
  { key: "lab.testresult.read", module: "lab", description: "Read test results (site-scoped)" },
  { key: "lab.testresult.create", module: "lab", description: "Create test results (site-scoped)" },
  { key: "lab.testresult.transition", module: "lab", description: "Transition test result state (progress/enter/review)" },
  { key: "lab.testresult.disposition", module: "lab", description: "Disposition a test result (human-only; AI MUST NEVER)" },
  // inspection (site-scoped, D6: simple)
  { key: "inspection.read", module: "inspection", description: "Read inspections (site-scoped)" },
  { key: "inspection.create", module: "inspection", description: "Record inspections (site-scoped)" },
  { key: "inspection.transition", module: "inspection", description: "Transition inspection state (pass/fail/conditional)" },
  // traceability (Phase 6, D1: query layer; D8: AI read-only)
  { key: "traceability.read", module: "traceability", description: "Read/query genealogy and traceability" },
  { key: "traceability.query-log.read", module: "traceability", description: "Read traceability query log (audit)" },
  // docs — Controlled Documents (Phase 7, global, D2 immutable when Effective)
  { key: "docs.document.read", module: "docs", description: "Read controlled documents" },
  { key: "docs.document.create", module: "docs", description: "Create controlled documents" },
  { key: "docs.document.transition", module: "docs", description: "Transition document state (review/approve/effective/supersede/obsolete)" },
  { key: "docs.document.approve", module: "docs", description: "Approve a document (human-only; AI MUST NEVER)" },
  // training (Phase 7)
  { key: "training.required.read", module: "training", description: "Read required training templates" },
  { key: "training.required.create", module: "training", description: "Create required training templates" },
  { key: "training.record.read", module: "training", description: "Read training records (site-scoped)" },
  { key: "training.record.create", module: "training", description: "Create training records (site-scoped)" },
  { key: "training.record.transition", module: "training", description: "Transition training record state (complete/expire)" },
  { key: "training.assessment.create", module: "training", description: "Record an assessment" },
  { key: "training.competency.read", module: "training", description: "Read competencies" },
  { key: "training.competency.authorize", module: "training", description: "Authorize a competency (human-only; AI MUST NEVER)" },
  // supplier audits (Phase 7, site-scoped)
  { key: "supplieraudit.read", module: "supplieraudit", description: "Read supplier audits (site-scoped)" },
  { key: "supplieraudit.create", module: "supplieraudit", description: "Create supplier audits (site-scoped)" },
  { key: "supplieraudit.transition", module: "supplieraudit", description: "Transition supplier audit state" },
  // equipment (Phase 8, site-scoped)
  { key: "equipment.read", module: "equipment", description: "Read equipment (site-scoped)" },
  { key: "equipment.create", module: "equipment", description: "Create equipment (site-scoped)" },
  { key: "equipment.update", module: "equipment", description: "Update equipment (site-scoped)" },
  { key: "equipment.maintenance.read", module: "equipment", description: "Read maintenance records" },
  { key: "equipment.maintenance.create", module: "equipment", description: "Create maintenance records" },
  { key: "equipment.maintenance.transition", module: "equipment", description: "Transition maintenance state" },
  { key: "equipment.calibration.read", module: "equipment", description: "Read calibration records" },
  { key: "equipment.calibration.create", module: "equipment", description: "Create calibration records" },
  { key: "equipment.qualification.read", module: "equipment", description: "Read qualifications" },
  { key: "equipment.qualification.create", module: "equipment", description: "Create qualifications" },
  { key: "equipment.qualification.transition", module: "equipment", description: "Transition qualification state" },
  { key: "equipment.qualification.approve", module: "equipment", description: "Approve a qualification (human-only; AI MUST NEVER)" },
  // cleanroom (Phase 9, site-scoped)
  { key: "cleanroom.read", module: "cleanroom", description: "Read cleanrooms (site-scoped)" },
  { key: "cleanroom.create", module: "cleanroom", description: "Create cleanrooms (site-scoped)" },
  { key: "cleanroom.result.create", module: "cleanroom", description: "Record monitoring results (site-scoped)" },
  { key: "cleanroom.excursion.transition", module: "cleanroom", description: "Transition excursion state" },
  // packaging (Phase 9, site-scoped)
  { key: "packaging.read", module: "packaging", description: "Read packaging records (site-scoped)" },
  { key: "packaging.create", module: "packaging", description: "Create packaging records (site-scoped)" },
  { key: "packaging.transition", module: "packaging", description: "Transition packaging state" },
  // sterilization (Phase 9, site-scoped; D4/D8: release is human-only)
  { key: "sterilization.read", module: "sterilization", description: "Read sterilization lots (site-scoped)" },
  { key: "sterilization.create", module: "sterilization", description: "Create sterilization lots (site-scoped)" },
  { key: "sterilization.transition", module: "sterilization", description: "Transition sterilization state" },
  { key: "sterilization.release", module: "sterilization", description: "Release a sterilization lot (human-only; AI MUST NEVER)" },
  // batch review (Phase 9, D5/D8: disposition is human-only)
  { key: "batchreview.read", module: "batchreview", description: "Read batch reviews (site-scoped)" },
  { key: "batchreview.transition", module: "batchreview", description: "Transition batch review state (QA review)" },
  { key: "batchreview.disposition", module: "batchreview", description: "Disposition a batch (human-only; AI MUST NEVER)" },
  // lean (Phase 10; D7: AI read-only)
  { key: "lean.read", module: "lean", description: "Read lean metrics, OEE, downtime, VSM" },
  { key: "lean.downtime.create", module: "lean", description: "Create downtime events" },
  { key: "lean.downtime.close", module: "lean", description: "Close downtime events (set endTime, compute duration)" },
  { key: "lean.vsm.create", module: "lean", description: "Create VSMs and manage nodes/edges" },
  // analytics (Phase 11; D11: AI gets analytics.read ONLY; D13: no AI feature in Phase 11)
  // D7: corporate.read is human-only (Executive Viewer / super_admin). D9: export human-only.
  // D2: snapshot.create declared but NOT implemented (live computation preferred); reserved for future.
  { key: "analytics.read", module: "analytics", description: "Read dashboards & reports for authorized sites (AI: yes, read-only)" },
  { key: "analytics.export", module: "analytics", description: "Export reports as CSV (human-only; AI MUST NEVER)" },
  { key: "analytics.corporate.read", module: "analytics", description: "Read corporate-aggregated (cross-site) analytics (human-only; AI MUST NEVER)" },
  { key: "analytics.snapshot.create", module: "analytics", description: "Create an AnalyticsSnapshot (human-only; RESERVED - not implemented in Phase 11)" },
];

// Role system keys (stable enum-like strings). The 19 PRD roles (PRD §3).
export const ROLE_SYSTEM_KEYS = [
  "super_admin",
  "site_admin",
  "plant_manager",
  "production_manager",
  "production_planner",
  "shift_supervisor",
  "operator",
  "quality_manager",
  "qa_reviewer",
  "quality_engineer",
  "lab_technician",
  "validation_engineer",
  "maintenance_manager",
  "maintenance_technician",
  "calibration_technician",
  "warehouse_logistics_manager",
  "lean_manager",
  "auditor",
  "executive_viewer",
] as const;

export type RoleSystemKey = (typeof ROLE_SYSTEM_KEYS)[number];

// Least-privilege default grants per role (ADR-0004 + docs/architecture/rbac-matrix.md).
// NO broad admin perms for convenience. Each entry maps a role systemKey to a list of permission keys.
// super_admin is the ONLY global-scope role and gets full Phase 1 permissions.
export const DEFAULT_ROLE_GRANTS: Record<RoleSystemKey, string[]> = {
  super_admin: [
    "identity.user.read", "identity.user.create", "identity.user.update", "identity.user.disable", "identity.user.reset-password",
    "identity.role.read", "identity.role.create", "identity.role.update",
    "identity.assignment.read", "identity.assignment.create", "identity.assignment.delete",
    "org.site.read", "org.site.create", "org.site.update", "org.site.deactivate",
    "org.department.read", "org.department.create", "org.department.update", "org.department.deactivate",
    "org.employee.read",
    "audit.read", "audit.export",
    "manufacturing.product.read", "manufacturing.product.create", "manufacturing.product.update",
    "manufacturing.revision.read", "manufacturing.revision.create", "manufacturing.revision.update", "manufacturing.revision.transition",
    "manufacturing.bom.read", "manufacturing.bom.update",
    "manufacturing.material.read", "manufacturing.material.create", "manufacturing.material.update",
    "manufacturing.materiallot.read", "manufacturing.materiallot.create", "manufacturing.materiallot.update", "manufacturing.materiallot.transition",
    "manufacturing.supplier.read", "manufacturing.supplier.create", "manufacturing.supplier.update",
    "manufacturing.materialsupplier.update",
    "production.routing.read", "production.routing.update",
    "production.workcenter.read", "production.workcenter.create", "production.workcenter.update",
    "production.workorder.read", "production.workorder.create", "production.workorder.update", "production.workorder.transition",
    "production.batch.read", "production.batch.create", "production.batch.transition",
    "production.devicelot.read", "production.devicelot.create", "production.devicelot.transition",
    "production.execution.read", "production.execution.create",
    "production.consumption.read", "production.consumption.create",
    "production.reservation.read", "production.reservation.create",
    "production.scrap.read", "production.scrap.create",
    "production.rework.read", "production.rework.create",
    "production.shift.read", "production.shift.create", "production.shift.update",
    "quality.ncr.read", "quality.ncr.create", "quality.ncr.transition",
    "quality.deviation.read", "quality.deviation.create", "quality.deviation.transition", "quality.deviation.approve",
    "quality.investigation.read", "quality.investigation.create", "quality.investigation.conclude",
    "quality.capa.read", "quality.capa.create", "quality.capa.transition", "quality.capa.close",
    "quality.change.read", "quality.change.create", "quality.change.transition", "quality.change.approve",
    "quality.risk.read", "quality.risk.create", "quality.risk.update",
    "lab.specification.read", "lab.specification.create", "lab.specification.transition", "lab.specification.approve", "lab.testmethod.read", "lab.testmethod.create", "lab.testmethod.transition", "lab.sample.read", "lab.sample.create", "lab.sample.transition", "lab.testresult.read", "lab.testresult.create", "lab.testresult.transition", "lab.testresult.disposition", "inspection.read", "inspection.create", "inspection.transition",
    "traceability.read", "traceability.query-log.read",
    "docs.document.read", "docs.document.create", "docs.document.transition", "docs.document.approve", "training.required.read", "training.required.create", "training.record.read", "training.record.create", "training.record.transition", "training.assessment.create", "training.competency.read", "training.competency.authorize", "supplieraudit.read", "supplieraudit.create", "supplieraudit.transition",
    "equipment.read", "equipment.create", "equipment.update", "equipment.maintenance.read", "equipment.maintenance.create", "equipment.maintenance.transition", "equipment.calibration.read", "equipment.calibration.create", "equipment.qualification.read", "equipment.qualification.create", "equipment.qualification.transition", "equipment.qualification.approve",
    "lean.read", "lean.downtime.create", "lean.downtime.close", "lean.vsm.create",
    "analytics.read", "analytics.export", "analytics.corporate.read", "analytics.snapshot.create",
    "session.sign-in", "session.sign-out",
  ],
  site_admin: [
    "identity.user.read", "identity.user.create", "identity.user.update", "identity.user.disable",
    "identity.role.read",
    "identity.assignment.read", "identity.assignment.create", "identity.assignment.delete",
    "org.site.read", "org.department.read", "org.department.create", "org.department.update", "org.department.deactivate",
    "org.employee.read",
    "audit.read",
    "manufacturing.product.read", "manufacturing.product.create", "manufacturing.product.update",
    "manufacturing.revision.read", "manufacturing.revision.create", "manufacturing.revision.update", "manufacturing.revision.transition",
    "manufacturing.bom.read", "manufacturing.bom.update",
    "manufacturing.material.read", "manufacturing.material.create", "manufacturing.material.update",
    "manufacturing.materiallot.read", "manufacturing.materiallot.create", "manufacturing.materiallot.update", "manufacturing.materiallot.transition",
    "manufacturing.supplier.read", "manufacturing.supplier.create", "manufacturing.supplier.update",
    "manufacturing.materialsupplier.update",
    "production.routing.read", "production.routing.update",
    "production.workcenter.read", "production.workcenter.create", "production.workcenter.update",
    "production.workorder.read", "production.workorder.create", "production.workorder.update", "production.workorder.transition",
    "production.batch.read", "production.batch.create", "production.batch.transition",
    "production.devicelot.read", "production.devicelot.create", "production.devicelot.transition",
    "production.execution.read", "production.execution.create",
    "production.consumption.read", "production.consumption.create",
    "production.reservation.read", "production.reservation.create",
    "production.scrap.read", "production.scrap.create",
    "production.rework.read", "production.rework.create",
    "production.shift.read", "production.shift.create", "production.shift.update",
    "lean.read",
    "analytics.read", "analytics.export",
    "session.sign-in", "session.sign-out",
  ],
  plant_manager: [
    "identity.user.read", "identity.role.read", "identity.assignment.read",
    "org.site.read", "org.department.read", "org.employee.read",
    "audit.read",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read",
    "manufacturing.supplier.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.workorder.create", "production.workorder.transition",
    "production.batch.read", "production.batch.create", "production.batch.transition",
    "production.devicelot.read", "production.execution.read",
    "production.consumption.read", "production.reservation.read",
    "production.scrap.read", "production.rework.read", "production.shift.read",
    "quality.ncr.read", "quality.deviation.read", "quality.investigation.read",
    "quality.capa.read", "quality.change.read", "quality.risk.read",
    "lab.specification.read", "lab.testmethod.read", "lab.sample.read", "lab.testresult.read", "inspection.read",
    "traceability.read",
    "docs.document.read", "training.required.read", "training.record.read", "training.competency.read", "supplieraudit.read",
    "equipment.read", "equipment.maintenance.read", "equipment.calibration.read", "equipment.qualification.read",
    "lean.read",
    "analytics.read", "analytics.export",
    "session.sign-in", "session.sign-out",
  ],
  production_manager: [
    "identity.user.read", "org.site.read", "org.department.read", "org.employee.read",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read", "manufacturing.materiallot.create",
    "manufacturing.supplier.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.workorder.create", "production.workorder.update", "production.workorder.transition",
    "production.batch.read", "production.batch.create", "production.batch.transition",
    "production.devicelot.read", "production.devicelot.create", "production.devicelot.transition",
    "production.execution.read", "production.execution.create",
    "production.consumption.read", "production.consumption.create",
    "production.reservation.read", "production.reservation.create",
    "production.scrap.read", "production.scrap.create",
    "production.rework.read", "production.rework.create",
    "production.shift.read",
    "quality.ncr.read", "quality.ncr.create",
    "quality.deviation.read", "quality.deviation.create",
    "quality.investigation.read", "quality.capa.read", "quality.change.read", "quality.risk.read",
    "traceability.read",
    "lean.read", "lean.downtime.create", "lean.downtime.close",
    "analytics.read", "analytics.export",
    "session.sign-in", "session.sign-out",
  ],
  production_planner: [
    "org.site.read", "org.department.read", "org.employee.read",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read",
    "manufacturing.supplier.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.workorder.create", "production.workorder.update", "production.workorder.transition",
    "production.batch.read", "production.batch.create",
    "production.devicelot.read", "production.reservation.read", "production.reservation.create",
    "production.shift.read",
    "session.sign-in", "session.sign-out",
  ],
  shift_supervisor: [
    "identity.user.read", "org.department.read", "org.employee.read",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.workorder.transition",
    "production.batch.read", "production.batch.create", "production.batch.transition",
    "production.devicelot.read", "production.devicelot.create", "production.devicelot.transition",
    "production.execution.read", "production.execution.create",
    "production.consumption.read", "production.consumption.create",
    "production.scrap.read", "production.scrap.create",
    "production.rework.read", "production.rework.create",
    "production.shift.read",
    "session.sign-in", "session.sign-out",
  ],
  operator: [
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.batch.read", "production.devicelot.read",
    "production.execution.read", "production.execution.create",
    "production.consumption.read", "production.consumption.create",
    "production.scrap.read", "production.scrap.create",
    "production.shift.read",
    "session.sign-in", "session.sign-out",
  ],
  quality_manager: [
    "identity.user.read", "identity.role.read", "identity.assignment.read",
    "org.site.read", "org.department.read", "org.employee.read",
    "audit.read", "audit.export",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.revision.transition",
    "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.material.update",
    "manufacturing.materiallot.read", "manufacturing.materiallot.transition",
    "manufacturing.supplier.read", "manufacturing.supplier.update",
    "manufacturing.materialsupplier.update",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.batch.read", "production.batch.transition",
    "production.devicelot.read", "production.execution.read",
    "production.consumption.read", "production.reservation.read",
    "production.scrap.read", "production.rework.read", "production.shift.read",
    "quality.ncr.read", "quality.ncr.create", "quality.ncr.transition",
    "quality.deviation.read", "quality.deviation.create", "quality.deviation.transition",
    "quality.investigation.read", "quality.investigation.create", "quality.investigation.conclude",
    "quality.capa.read", "quality.capa.create", "quality.capa.transition", "quality.capa.close",
    "quality.change.read", "quality.change.create", "quality.change.transition",
    "quality.risk.read", "quality.risk.create", "quality.risk.update",
    "lab.specification.read", "lab.specification.create", "lab.specification.transition", "lab.specification.approve", "lab.testmethod.read", "lab.testmethod.create", "lab.testmethod.transition", "lab.sample.read", "lab.sample.create", "lab.sample.transition", "lab.testresult.read", "lab.testresult.create", "lab.testresult.transition", "lab.testresult.disposition", "inspection.read", "inspection.create", "inspection.transition",
    "traceability.read", "traceability.query-log.read",
    "docs.document.read", "docs.document.create", "docs.document.transition", "docs.document.approve", "training.required.read", "training.required.create", "training.record.read", "training.record.create", "training.record.transition", "training.assessment.create", "training.competency.read", "training.competency.authorize", "supplieraudit.read", "supplieraudit.create", "supplieraudit.transition",
    "equipment.read", "equipment.create", "equipment.update", "equipment.maintenance.read", "equipment.maintenance.create", "equipment.maintenance.transition", "equipment.calibration.read", "equipment.calibration.create", "equipment.qualification.read", "equipment.qualification.create", "equipment.qualification.transition", "equipment.qualification.approve",
    "lean.read",
    "analytics.read", "analytics.export",
    "session.sign-in", "session.sign-out",
  ],
  qa_reviewer: [
    "audit.read", "identity.user.read", "org.site.read", "org.department.read", "org.employee.read",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read",
    "manufacturing.supplier.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.batch.read", "production.devicelot.read",
    "production.execution.read", "production.consumption.read", "production.reservation.read",
    "production.scrap.read", "production.rework.read", "production.shift.read",
    "quality.ncr.read", "quality.ncr.transition",
    "quality.deviation.read", "quality.deviation.transition", "quality.deviation.approve",
    "quality.investigation.read", "quality.investigation.conclude",
    "quality.capa.read", "quality.capa.transition", "quality.capa.close",
    "quality.change.read", "quality.change.transition", "quality.change.approve",
    "quality.risk.read", "quality.risk.update",
    "lab.specification.read", "lab.specification.create", "lab.specification.transition", "lab.specification.approve", "lab.testmethod.read", "lab.testmethod.create", "lab.testmethod.transition", "lab.sample.read", "lab.testresult.read", "lab.testresult.transition", "lab.testresult.disposition", "inspection.read", "inspection.transition",
    "traceability.read", "traceability.query-log.read",
    "analytics.read",
    "session.sign-in", "session.sign-out",
  ],
  quality_engineer: [
    "audit.read", "identity.user.read", "org.site.read", "org.department.read", "org.employee.read",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.revision.transition",
    "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read", "manufacturing.materiallot.transition",
    "manufacturing.supplier.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.batch.read", "production.batch.transition",
    "production.devicelot.read", "production.execution.read",
    "production.consumption.read", "production.scrap.read", "production.rework.read", "production.shift.read",
    "quality.ncr.read", "quality.ncr.create", "quality.ncr.transition",
    "quality.deviation.read", "quality.deviation.create", "quality.deviation.transition",
    "quality.investigation.read", "quality.investigation.create", "quality.investigation.conclude",
    "quality.capa.read", "quality.capa.create", "quality.capa.transition", "quality.capa.close",
    "quality.change.read", "quality.change.create", "quality.change.transition",
    "quality.risk.read", "quality.risk.create", "quality.risk.update",
    "lab.specification.read", "lab.specification.create", "lab.specification.transition", "lab.specification.approve", "lab.testmethod.read", "lab.testmethod.create", "lab.testmethod.transition", "lab.sample.read", "lab.sample.create", "lab.sample.transition", "lab.testresult.read", "lab.testresult.create", "lab.testresult.transition", "lab.testresult.disposition", "inspection.read", "inspection.create", "inspection.transition",
    "traceability.read",
    "docs.document.read", "docs.document.create", "docs.document.transition", "docs.document.approve", "training.required.read", "training.required.create", "training.record.read", "training.record.create", "training.record.transition", "training.assessment.create", "training.competency.read", "training.competency.authorize", "supplieraudit.read", "supplieraudit.create", "supplieraudit.transition",
    "equipment.read", "equipment.create", "equipment.update", "equipment.maintenance.read", "equipment.maintenance.create", "equipment.maintenance.transition", "equipment.calibration.read", "equipment.calibration.create", "equipment.qualification.read", "equipment.qualification.create", "equipment.qualification.transition", "equipment.qualification.approve",
    "lean.read",
    "analytics.read", "analytics.export",
    "session.sign-in", "session.sign-out",
  ],
  lab_technician: [
    "manufacturing.material.read", "manufacturing.materiallot.read",
    "lab.specification.read", "lab.testmethod.read", "lab.sample.read", "lab.sample.create", "lab.sample.transition", "lab.testresult.read", "lab.testresult.create", "lab.testresult.transition", "inspection.read", "inspection.create", "inspection.transition",
    "session.sign-in", "session.sign-out",
  ],
  validation_engineer: [
    "org.site.read", "org.department.read", "audit.read",
    "session.sign-in", "session.sign-out",
  ],
  maintenance_manager: [
    "identity.user.read", "org.site.read", "org.department.read", "org.employee.read",
    "manufacturing.product.read", "manufacturing.material.read", "manufacturing.materiallot.read",
    "equipment.read", "equipment.create", "equipment.update", "equipment.maintenance.read", "equipment.maintenance.create", "equipment.maintenance.transition", "equipment.calibration.read", "equipment.calibration.create", "equipment.qualification.read", "equipment.qualification.create", "equipment.qualification.transition", "equipment.qualification.approve",
    "analytics.read",
    "session.sign-in", "session.sign-out",
  ],
  maintenance_technician: [
    "session.sign-in", "session.sign-out",
  ],
  calibration_technician: [
    "session.sign-in", "session.sign-out",
  ],
  warehouse_logistics_manager: [
    "identity.user.read", "org.site.read", "org.department.read", "org.employee.read",
    "manufacturing.material.read", "manufacturing.material.create", "manufacturing.material.update",
    "manufacturing.materiallot.read", "manufacturing.materiallot.create", "manufacturing.materiallot.update", "manufacturing.materiallot.transition",
    "manufacturing.supplier.read",
    "session.sign-in", "session.sign-out",
  ],
  lean_manager: [
    "org.site.read", "org.department.read", "audit.read",
    "lean.read",
    "analytics.read", "analytics.export",
    "session.sign-in", "session.sign-out",
  ],
  auditor: [
    "audit.read", "audit.export",
    "identity.user.read", "identity.role.read", "identity.assignment.read",
    "org.site.read", "org.department.read", "org.employee.read",
    "manufacturing.product.read", "manufacturing.revision.read", "manufacturing.bom.read",
    "manufacturing.material.read", "manufacturing.materiallot.read",
    "manufacturing.supplier.read",
    "production.routing.read", "production.workcenter.read",
    "production.workorder.read", "production.batch.read", "production.devicelot.read",
    "production.execution.read", "production.consumption.read", "production.reservation.read",
    "production.scrap.read", "production.rework.read", "production.shift.read",
    "quality.ncr.read", "quality.deviation.read", "quality.investigation.read",
    "quality.capa.read", "quality.change.read", "quality.risk.read",
    "lab.specification.read", "lab.testmethod.read", "lab.sample.read", "lab.testresult.read", "inspection.read",
    "traceability.read", "traceability.query-log.read",
    "docs.document.read", "training.required.read", "training.record.read", "training.competency.read", "supplieraudit.read",
    "equipment.read", "equipment.maintenance.read", "equipment.calibration.read", "equipment.qualification.read",
    "lean.read",
    "analytics.read", "analytics.export",
    "session.sign-in", "session.sign-out",
  ],
  executive_viewer: [
    "analytics.read", "analytics.corporate.read",
    "org.site.read",
    "manufacturing.product.read", "production.workorder.read", "production.batch.read",
    "quality.ncr.read", "quality.deviation.read", "quality.capa.read", "quality.change.read", "quality.risk.read",
    "lean.read",
    "session.sign-in", "session.sign-out",
  ],
};

// Human-readable role display names (i18n keys; the UI resolves via message catalogs).
export const ROLE_DISPLAY_NAMES: Record<RoleSystemKey, string> = {
  super_admin: "Super Administrator",
  site_admin: "Site Administrator",
  plant_manager: "Plant Manager",
  production_manager: "Production Manager",
  production_planner: "Production Planner",
  shift_supervisor: "Shift Supervisor",
  operator: "Operator",
  quality_manager: "Quality Manager",
  qa_reviewer: "QA Reviewer/Approver",
  quality_engineer: "Quality Engineer",
  lab_technician: "Laboratory Technician",
  validation_engineer: "Validation Engineer",
  maintenance_manager: "Maintenance Manager",
  maintenance_technician: "Maintenance Technician",
  calibration_technician: "Calibration Technician",
  warehouse_logistics_manager: "Warehouse/Logistics Manager",
  lean_manager: "Lean Manager",
  auditor: "Auditor",
  executive_viewer: "Executive Viewer",
};

// User status state machine (domain invariant).
export const USER_STATUSES = ["ACTIVE", "LOCKED", "DISABLED"] as const;
export type UserStatus = (typeof USER_STATUSES)[number];

export const SITE_STATUSES = ["ACTIVE", "INACTIVE"] as const;
export type SiteStatus = (typeof SITE_STATUSES)[number];

export const AUDIT_OUTCOMES = ["SUCCESS", "FAILURE", "DENIED"] as const;
export type AuditOutcome = (typeof AUDIT_OUTCOMES)[number];

export const LOCALES = ["en", "fr", "ar"] as const;
export type Locale = (typeof LOCALES)[number];
