"use client";
import { useTranslations } from "next-intl";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
export default function QueryLogPage() {
  const t = useTranslations("traceability");
  const { data, isLoading } = useQuery({ queryKey: ["traceability-query-log"], queryFn: async () => { const res = await fetch("/api/traceability/query-log?pageSize=100", { credentials: "same-origin" }); if (!res.ok) throw new Error("Failed"); const json = await res.json(); return json.data as Array<{ id: string; queryType: string; rootEntityType: string; scenario: string | null; executedAt: string; requester: { name: string | null; email: string } | null }>; } });
  return (<div className="space-y-6"><div><h1 className="text-2xl font-bold tracking-tight">{t("queryLog.title")}</h1><p className="text-sm text-muted-foreground">{t("queryLog.subtitle")}</p></div><Card><CardHeader><CardTitle className="text-base">{t("queryLog.title")}</CardTitle></CardHeader><CardContent>{isLoading ? <p className="text-sm text-muted-foreground">Loading...</p> : data && data.length > 0 ? (<div className="max-h-[32rem] overflow-auto rounded-md border"><Table><TableHeader className="sticky top-0 bg-card"><TableRow><TableHead>Type</TableHead><TableHead>Root Entity</TableHead><TableHead>Scenario</TableHead><TableHead>Actor</TableHead><TableHead>Executed</TableHead></TableRow></TableHeader><TableBody>{data.map((q) => (<TableRow key={q.id}><TableCell className="text-xs"><Badge variant="outline">{q.queryType}</Badge></TableCell><TableCell className="font-mono text-xs">{q.rootEntityType}</TableCell><TableCell className="text-xs">{q.scenario ?? "-"}</TableCell><TableCell className="text-xs">{q.requester?.name ?? q.requester?.email ?? "-"}</TableCell><TableCell className="text-xs text-muted-foreground">{new Date(q.executedAt).toLocaleString()}</TableCell></TableRow>))}</TableBody></Table></div>) : <p className="text-sm text-muted-foreground">{t("queryLog.noData")}</p>}</CardContent></Card></div>);
}
